core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls

from core import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls")),
    path("accounts/", include("accounts.urls")),
    path("auth/", include("allauth.urls")),
    path("orders/", include("orders.urls")),
    path("pay/", include("payment.urls")),
] + debug_toolbar_urls()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
"""store urls"""

from django.urls import path
from store.views import (
    homepage,
    explore,
    list_categories,
    list_all,
    list_best_sellers,
    list_new_arrivals,
    review_form,
    show_category,
    show_product,
    search_products,
    product_by_tag,
    terms_and_conditions,
    privacy
)

app_name = "store"
urlpatterns = [
    path("", homepage, name="home"),
    path("explore/", explore, name="explore"),
    path("categories/", list_categories, name="categories"),
    path("category/<slug:slug>/", show_category, name="show-category"),
    path("products/", list_all, name="all-products"),
    path("product/<slug:slug>/", show_product, name="show-product"),
    path("best-sellers/", list_best_sellers, name="best-sellers"),
    path("new-arrivals/", list_new_arrivals, name="new-arrivals"),
    path("review/<int:id>/", review_form, name="review-form"),
    path("search/", search_products, name="search"),
    path("tag/<slug:slug>/", product_by_tag, name="products-by-tag"),
    path("terms/", terms_and_conditions, name="terms"),
    path("privacy-policy/", privacy, name="privacy"),
    # path("checkout/<int:order_id>/", initiate_payment, name="checkout"),
    # path("payment/success/", payment_success, name="payment-success"),
    # path("payment/failure/", payment_failure, name="payment-failure"),
    # path("track-event/", track_event, name="track-event"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- System fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500&display=swap">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <!-- Favicons -->
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'fav/favicon-32x32.png' %}">

  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
  <script src="//unpkg.com/alpinejs" defer></script>
  <title>{% block title %}Chill Monkey Store{% endblock title %}</title>
</head>

<body class="min-h-screen bg-white text-gray-900">
  {% include "./components/navigation.html" %}

  <!-- Main Content -->
  <div class="grid xl:grid-cols-6 gap-4 px-4 mt-4">
    <aside x-data="{ open: false }"
      class="sticky top-16 xl:col-span-1 xl:block  border-2 border-gray-300 lg:border-0 rounded-lg ">
      <!-- Mobile Toggle Button -->
      <button @click="open = !open"
        class="xl:hidden flex justify-between items-center w-full px-4 py-2  rounded-md bg-white hover:bg-gray-200 transition -z-50 rounded-bl-none rounded-br-none">
        <span class="font-medium">Browse Categories & Tags</span>
        <svg x-show="!open" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
          stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
        </svg>
        <svg x-show="open" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
          stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 15l7-7 7 7"></path>
        </svg>
      </button>

      <!-- Sidebar Content -->
      <div :class="open ? 'block' : 'hidden'" class="xl:block mt-0 lg:mt-8 bg-white flex flex-col mx-auto -z-50">
        <!-- Search Bar -->
        <form action="{% url 'store:search' %}" method="get" class="flex justify-center px-0 mx-0 mb-2 pt-4">
          <input
            class="p-2 rounded-l-md border border-gray-300 focus:outline-none focus:ring focus:ring-gray-300 text-black"
            type="text" name="query" placeholder="Search">
          <button class="p-2 bg-gray-100 rounded-r-md border border-l-0 border-gray-300 hover:bg-gray-200 transition"
            type="submit">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="currentColor">
              <path
                d="M11 2C15.968 2 20 6.032 20 11C20 15.968 15.968 20 11 20C6.032 20 2 15.968 2 11C2 6.032 6.032 2 11 2ZM11 18C14.8675 18 18 14.8675 18 11C18 7.1325 14.8675 4 11 4C7.1325 4 4 7.1325 4 11C4 14.8675 7.1325 18 11 18ZM19.4853 18.0711L22.3137 20.8995L20.8995 22.3137L18.0711 19.4853L19.4853 18.0711Z" />
            </svg>
          </button>
        </form>

        <!-- Categories -->
        <div class="text-center">
          <h2 class="text-lg font-medium my-4">Categories</h2>
          <div class="flex flex-col">
            {% for category in categories %}
            <a href="{% url 'store:show-category' category.slug %}"
              class="border text-sm font-thin border-gray-500 text-gray-800 hover:text-white rounded-md p-2 m-1 hover:bg-gray-500 transition">
              {{ category.name }}
            </a>
            {% endfor %}
          </div>
        </div>

        <!-- Tags -->
        <div class="mt-8 text-center">
          <h2 class="text-lg font-medium mb-4">Tags</h2>
          <div class="flex flex-wrap justify-center">
            {% for tag in tags %}
            <a href="{% url 'store:products-by-tag' tag.slug %}"
              class="border text-sm font-thin border-gray-500 text-gray-800 hover:text-white uppercase m-1 p-2 rounded-md hover:bg-gray-500 transition">
              {{ tag.name }}
            </a>
            {% endfor %}
          </div>
        </div>
      </div>
    </aside>

    <main class="col-span-full lg:col-span-5 min-h-[70vh]">
      {% block content %}{% endblock %}
    </main>
  </div>

  <!-- Messages -->
  <div id="message-box" class="fixed bottom-4 right-4 w-64">
    <ul class="space-y-2 messages">
      {% for message in messages %}
      <li class="bg-gray-100 p-3 text-sm rounded shadow-md fade-message message">{{ message }}</li>
      {% endfor %}
    </ul>
  </div>

  <!-- Footer -->
  {% include "./components/footer.html" %}

  <script src="{% static 'js/script.js' %}"></script>
</body>

</html>