accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"
urlpatterns = [
    path("register/", views.sign_up, name="sign_up"),
    path("", views.sign_in, name="sign_in"),
    path("logout/", views.logout_user, name="logout"),
]

core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls

from core import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls")),
    path("accounts/", include("accounts.urls")),
    path("auth/", include("allauth.urls")),
    path("orders/", include("orders.urls")),
    path("pay/", include("payment.urls")),
] + debug_toolbar_urls()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'
urlpatterns = [
    path('summary/', views.bag_summary, name='summary'),
    path('add/', views.bag_add, name='bag_add'),
    path('update/', views.bag_update, name='bag_update'),
    path('delete/', views.bag_delete, name='bag_delete'),
    path('clear/', views.bag_clear, name='bag_clear'),
    path('orders/',views.view_orders, name="view_orders")
]

store/urls.py
"""store urls"""

from django.urls import path
from store.views import (
    homepage,
    explore,
    list_categories,
    list_all,
    list_best_sellers,
    list_new_arrivals,
    review_form,
    show_category,
    show_product,
    search_products,
    product_by_tag,
    terms_and_conditions,
    privacy
)

app_name = "store"
urlpatterns = [
    path("", homepage, name="home"),
    path("explore/", explore, name="explore"),
    path("categories/", list_categories, name="categories"),
    path("category/<slug:slug>/", show_category, name="show-category"),
    path("products/", list_all, name="all-products"),
    path("product/<slug:slug>/", show_product, name="show-product"),
    path("best-sellers/", list_best_sellers, name="best-sellers"),
    path("new-arrivals/", list_new_arrivals, name="new-arrivals"),
    path("review/<int:id>/", review_form, name="review-form"),
    path("search/", search_products, name="search"),
    path("tag/<slug:slug>/", product_by_tag, name="products-by-tag"),
    path("terms/", terms_and_conditions, name="terms"),
    path("privacy-policy/", privacy, name="privacy"),
    # path("checkout/<int:order_id>/", initiate_payment, name="checkout"),
    # path("payment/success/", payment_success, name="payment-success"),
    # path("payment/failure/", payment_failure, name="payment-failure"),
    # path("track-event/", track_event, name="track-event"),
]

templates/components/footer.html
<footer
    class="w-full min-h-[25vh] flex flex-col justify-evenly items-center font-raleway font-light text-gray-300 bg-neutral-900">
    <ul class="grid grid-cols-2 lg:grid-cols-3 gap-4 text-center mt-8">
        <a class="hover:text-amber-300 hover:underline duration-200" href="{% url 'store:explore' %}">Explore</a>
        <a class="hover:text-amber-300 hover:underline duration-200" href="{% url 'store:categories' %}">Categories</a>
        <a class="hover:text-amber-300 hover:underline duration-200" href="{% url 'accounts:sign_up' %}">Sign Up</a>
        <a class="hover:text-amber-300 hover:underline duration-200" href="{% url 'accounts:sign_in' %}">Sign In</a>
        <a class="hover:text-amber-300 hover:underline duration-200" href="{% url 'store:privacy' %}">Privacy Policy</a>
        <a class="hover:text-amber-300 hover:underline duration-200" href="{% url 'store:terms' %}">Terms &
            Conditions</a>
    </ul>

    <div class="animate-pulse text-sm py-4">Built by <a class="font-medium" href="https://www.therishabhdev.com/"
            target="_blank">Rishabhdev</a>.</div>

    <div class="pb-4 text-xs opacity-80">
        <span>© 2024 Chill Monkey Store.</span>
        <span>All Rights Reserved.</span>
    </div>
</footer>

templates/components/navigation.html
<nav x-data="{ open: false }"
    class="flex items-center justify-between bg-white shadow-md shadow-black/5 py-2 px-8 md:px-8 sticky top-0 z-50">
    <!-- Logo -->
    <header class="block">
        <a href="{% url 'store:home' %}" class="text-3xl font-extralight">
            Chill Monkey Store
        </a>
    </header>

    <!-- Mobile Menu Toggle -->
    <div class="lg:hidden">
        <button @click="open = !open" class="text-white focus:outline-none">
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
            </svg>
        </button>
    </div>

    <!-- Desktop Navigation -->
    <div class="hidden lg:flex justify-evenly lg:w-1/2 items-center text-sm pr-8 space-x-4">
        <a href="{% url 'store:home' %}"
            class="px-4 py-2 border border-transparent hover:border-white rounded-lg duration-200">Home</a>
        <a href="{% url 'store:explore' %}"
            class="px-4 py-2 border border-transparent hover:border-white rounded-lg duration-200">Explore</a>
        <a href="{% url 'store:categories' %}"
            class="px-4 py-2 border border-transparent hover:border-white rounded-lg duration-200">Categories</a>

        {% if not user.is_authenticated %}
        <a href="{% url 'accounts:sign_in' %}"
            class="px-4 py-2 border border-transparent hover:border-white rounded-lg duration-200">Sign
            in</a>
        <a href="{% url 'accounts:sign_up' %}"
            class="px-4 py-2 border border-transparent hover:border-white rounded-lg duration-200">Sign
            up</a>
        {% else %}
        <a href="{% url 'orders:summary' %}"
            class="px-4 py-2 border border-transparent hover:border-white rounded-lg duration-200  gap-x-2 grid grid-cols-2 items-center"><svg
                xmlns="http://www.w3.org/2000/svg" width="24px" viewBox="0 0 24 24" fill="currentColor">
                <path
                    d="M12.0002 2C15.8662 2 19.0002 5.13401 19.0002 9H20.0742C20.5967 9 21.0311 9.40231 21.0712 9.9233L21.9174 20.9233C21.9597 21.474 21.5477 21.9547 20.997 21.9971L20.9203 22H3.08008C2.52779 22 2.08008 21.5523 2.08008 21L2.08302 20.9233L2.92918 9.9233C2.96925 9.40231 3.4037 9 3.92623 9H5.0002C5.0002 5.13401 8.13421 2 12.0002 2ZM19.1472 11H4.8522L4.1592 20H19.8402L19.1472 11ZM14.0002 13V15H10.0002V13H14.0002ZM12.0002 4C9.31145 4 7.11838 6.12231 7.00482 8.78311L7.0002 9H17.0002C17.0002 6.31124 14.8779 4.11818 12.2171 4.00462L12.0002 4Z">
                </path>
            </svg>Bag</a>
        <a href="{% url 'orders:view_orders' %}">My Orders</a>
        <a href="{% url 'accounts:logout' %}"
            class="ml-8 px-4 py-2 border border-transparent text-white hover:bg-red-800 bg-red-600 rounded-lg duration-200">Logout</a>
        {% endif %}
    </div>

    <!-- Mobile Navigation -->
    <div x-show="open" @click.away="open = false" class="absolute top-12 left-0 w-full bg-neutral-800 lg:hidden">
        <a href="{% url 'store:home' %}"
            class="block px-4 py-2 text-center hover:underline hover:text-violet-400">Home</a>
        <a href="{% url 'store:explore' %}"
            class="block px-4 py-2 text-center hover:underline hover:text-violet-400">Explore</a>
        <a href="{% url 'store:categories' %}"
            class="block px-4 py-2 text-center hover:underline hover:text-violet-400">Categories</a>

        {% if not user.is_authenticated %}
        <a href="{% url 'accounts:sign_in' %}"
            class="block px-4 py-2 text-center hover:underline hover:text-violet-400">Sign in</a>
        <a href="{% url 'accounts:sign_up' %}"
            class="block px-4 py-2 text-center hover:underline hover:text-violet-400">Sign up</a>
        {% else %}
        <a href="{% url 'orders:summary' %}"
            class="block px-4 py-2 text-center hover:underline hover:text-violet-400">Bag</a>
        <a href="{% url 'accounts:logout' %}"
            class="block px-4 py-2 text-center hover:underline hover:text-violet-400">Logout</a>
        {% endif %}
    </div>
</nav>